version: '3.8'

services:
  auth-adventure:
    build: .
    container_name: auth_adventure
    ports:
      - "8008:8008"
    restart: unless-stopped
    networks:
      - ctf_network
    labels:
      - "ctf.domain=auth-adventure.ctf.dscjssstuniv.in"
      - "ctf.port=8008"
      - "ctf.challenge=Auth Adventure"

networks:
  ctf_network:
    external: true