version: '3.8'

services:
  stranger-things:
    build: .
    container_name: stranger_things
    ports:
      - "8013:8000"
    restart: unless-stopped
    networks:
      - ctf_network
    labels:
      - "ctf.domain=stranger-things.ctf.dscjssstuniv.in"
      - "ctf.port=8013"
      - "ctf.challenge=Stranger Things"

networks:
  ctf_network:
    external: true