version: '3.8'

services:
  plain-sight:
    build: .
    container_name: plain_sight
    ports:
      - "8012:8000"
    restart: unless-stopped
    networks:
      - ctf_network
    labels:
      - "ctf.domain=plain-sight.ctf.dscjssstuniv.in"
      - "ctf.port=8012"
      - "ctf.challenge=Plain Sight"

networks:
  ctf_network:
    external: true
