version: '3.8'

services:
  nothing-works:
    build: .
    container_name: nothing_works
    ports:
      - "8010:8000"
    restart: unless-stopped
    networks:
      - ctf_network
    labels:
      - "ctf.domain=nothing-works.ctf.dscjssstuniv.in"
      - "ctf.port=8010"
      - "ctf.challenge=Nothing Works"

networks:
  ctf_network:
    external: true
