version: '3.8'

services:
  curl-unfurl:
    build: .
    container_name: curl-unfurl
    ports:
      - "5003:5000"
    restart: unless-stopped
    networks:
      - ctf_network
    labels:
      - "ctf.domain=curl-unfurl.ctf.dscjssstuniv.in"
      - "ctf.port=5003"
      - "ctf.challenge=Curl Unfurl"

networks:
  ctf_network:
    external: true
