version: '3.8'

services:
  time-window-exposure:
    build: .
    container_name: time_window_exposure
    ports:
      - "8003:5000"
    restart: unless-stopped
    networks:
      - ctf_network
    labels:
      - "ctf.domain=time-window-exposure.ctf.dscjssstuniv.in"
      - "ctf.port=8003"
      - "ctf.challenge=Time Window Exposure"

networks:
  ctf_network:
    external: true