version: '3.8'

services:
  wrong-password:
    build: .
    container_name: wrong_password
    ports:
      - "8014:8000"
    restart: unless-stopped
    networks:
      - ctf_network
    labels:
      - "ctf.domain=wrong-password.ctf.dscjssstuniv.in"
      - "ctf.port=8014"
      - "ctf.challenge=Wrong Password"

networks:
  ctf_network:
    external: true
