version: '3.8'

services:
  robots-watching:
    build: .
    container_name: robots-watching
    ports:
      - "5001:5000"
    restart: unless-stopped
    networks:
      - ctf_network
    environment:
      - FLASK_ENV=production
    labels:
      - "ctf.domain=robots-watching.ctf.dscjssstuniv.in"
      - "ctf.port=5001"
      - "ctf.challenge=Robots Watching"

networks:
  ctf_network:
    external: true
