version: '3.8'

services:
  cookie-recipe:
    build: .
    container_name: cookie-recipe
    ports:
      - "5002:5000"
    restart: unless-stopped
    networks:
      - ctf_network
    labels:
      - "ctf.domain=cookie-recipe.ctf.dscjssstuniv.in"
      - "ctf.port=5002"
      - "ctf.challenge=Cookie Recipe"

networks:
  ctf_network:
    external: true
