version: '3.8'

services:
  overthinker:
    build: .
    container_name: overthinker
    ports:
      - "8011:8000"
    restart: unless-stopped
    networks:
      - ctf_network
    labels:
      - "ctf.domain=overthinker.ctf.dscjssstuniv.in"
      - "ctf.port=8011"
      - "ctf.challenge=Overthinker"

networks:
  ctf_network:
    external: true