version: '3.8'

services:
  secure-portal:
    build: .
    container_name: secure_portal
    ports:
      - "8007:8007"
    restart: unless-stopped
    networks:
      - ctf_network
    labels:
      - "ctf.domain=secure-portal.ctf.dscjssstuniv.in"
      - "ctf.port=8007"
      - "ctf.challenge=Secure Portal"

networks:
  ctf_network:
    external: true