version: '3.8'

services:
  flag-in-cache:
    build: .
    container_name: flag_in_cache
    ports:
      - "8009:8000"
    restart: unless-stopped
    networks:
      - ctf_network
    labels:
      - "ctf.domain=flag-in-cache.ctf.dscjssstuniv.in"
      - "ctf.port=8009"
      - "ctf.challenge=Flag in Cache"

networks:
  ctf_network:
    external: true