version: '3.8'

services:
  echo-chamber:
    build: .
    ports:
      - "8017:80"
    container_name: echo_chamber_web
    restart: unless-stopped
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    volumes:
      - ./flag.txt:/flag:ro