services:
  regex-master:
    build: .
    container_name: regex_master
    ports:
      - "8006:8006"
    restart: unless-stopped
    command: sh -c "socat TCP-LISTEN:8006,reuseaddr,fork EXEC:'python3 -u regex_master.py',pty,stderr"
    stdin_open: true
    tty: true